# Generated by Django 4.0.4 on 2022-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_time',
            field=models.DateTimeField(help_text='The is completion time', null=True),
        ),
    ]
